### ISSUE TITLE
Add support for Linux Mint-based systems

### ISSUE THREAD

**Issue by mkurnikov** [unixpackage/unixpackage#2]
I'm using LMDE2, Linux Mint version of Debian. On my system `hitch init` fails with:

```
Platform linuxmint is not supported yet.
```

as expected from unsupported platform. 

If I understand correctly, `unixpackage` doesn't differentiate Debian and Ubuntu packages, and support both at once. But basically LMDE2 uses Debian repositories for `apt-get`, and Linux Mint uses Ubuntu repos. 

Please add some kind of a symlink from `linuxmint` to `debian/ubuntu` to support that systems too.

**Comment by crdoconnor** [comment]
Yikes. I thought that Linux Mint reported itself as Ubuntu. Let me fix that quickly.

**Comment by crdoconnor** [comment]
Ok 'linuxmint' should now be treated as 'ubuntu' in the latest version of unixpackage on pypi.

Can you try again?

If you have any other problems when running "hitch init" or "hitch test" feel free to report them here. I'll try to fix them too.

**Comment by mkurnikov** [comment]
It works! Thank you very much for the quick fix!

**Comment by crdoconnor** [comment]
Thank you for reporting!

If you see any other bugs or even behavior you didn't expect, please do raise another issue. I'll try to  be quick about fixing anything else you see too.
